# Generated by Django 2.0.3 on 2019-05-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_tabela'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela',
            name='campo2',
            field=models.IntegerField(default=0),
        ),
    ]
